CREATE TABLE TEST_CUSTOMER
(
ID NUMBER NOT NULL,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
DATE_OF_BIRTH DATE,
EMAIL VARCHAR(20),
PASSWORD VARCHAR(256),
LAST_UPDATED_BY VARCHAR(30) NOT NULL,
LAST_UPDATED DATE NOT NULL,
OPTLOCK_VERSION NUMBER NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TEST_TRAVELLER
(
ID NUMBER NOT NULL,
FIRST_NAME VARCHAR(20),
MIDDLE_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
PASSPORT_NUMBER VARCHAR(20),
DATE_OF_BIRTH DATE,
CUSTOMER_ID NUMBER,
LAST_UPDATED_BY VARCHAR(30) NOT NULL,
LAST_UPDATED DATE NOT NULL,
OPTLOCK_VERSION NUMBER NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT FK_CUSTOMER_TRAVELLER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES TEST_CUSTOMER(ID)
);

CREATE TABLE TEST_FLIGHTS
(
  ID NUMBER NOT NULL,
  SOURCE VARCHAR(20) NOT NULL,
  DESTINATION VARCHAR(20) NOT NULL,
  DEPARTURE_DATE DATE NOT NULL,
  ARRIVAL_DATE DATE NOT NULL,
  BASE_FARE NUMBER(7,2) NOT NULL,
  LAST_UPDATED_BY VARCHAR(30) NOT NULL,
  LAST_UPDATED DATE NOT NULL,
  OPTLOCK_VERSION NUMBER NOT NULL,
  PRIMARY KEY (ID)

);

CREATE TABLE TEST_FLIGHT_SEGMENT
(
  ID INT  NOT NULL,
  FLIGHT_NUMBER VARCHAR(20) NOT NULL,
  OPERATING_AIRLINES VARCHAR(20) NOT NULL,
  SOURCE VARCHAR(20) NOT NULL,
  DESTINATION VARCHAR(20) NOT NULL,
  DEPARTURE_DATE DATE  NOT NULL,
  ARRIVAL_DATE DATE  NOT NULL,
  FLIGHT_ID INT,
  LAST_UPDATED_BY VARCHAR(30) NOT NULL,
  LAST_UPDATED DATE NOT NULL,
  OPTLOCK_VERSION INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_FLIGHTS
        FOREIGN KEY (FLIGHT_ID)
        REFERENCES TEST_FLIGHTS(ID)
);

CREATE TABLE TEST_ITINERARY
(
  ID NUMBER NOT NULL,
  SOURCE VARCHAR(20) NOT NULL,
  DESTINATION VARCHAR(20) NOT NULL,
  DEPARTURE_DATE DATE NOT NULL,
  ARRIVAL_DATE DATE NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  BASE_FARE NUMBER(7,2) NOT NULL,
  CUSTOMER_ID NUMBER NOT NULL,
  LAST_UPDATED_BY VARCHAR(30) NOT NULL,
  LAST_UPDATED DATE NOT NULL,
  OPTLOCK_VERSION NUMBER NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_ITINERARY_CUS
          FOREIGN KEY (CUSTOMER_ID)
          REFERENCES TEST_CUSTOMER(ID)

);

CREATE TABLE TEST_ITINERARY_SEGMENT
(
  ID NUMBER NOT NULL,
  FLIGHT_NUMBER VARCHAR(20) NOT NULL,
  OPERATING_AIRLINES VARCHAR(20) NOT NULL,
  SOURCE VARCHAR(20) NOT NULL,
  DESTINATION VARCHAR(20) NOT NULL,
  DEPARTURE_DATE DATE  NOT NULL,
  ARRIVAL_DATE DATE  NOT NULL,
  LEG_NUMBER INT,
  ITINERARY_ID INT,
  LAST_UPDATED_BY VARCHAR(30) NOT NULL,
  LAST_UPDATED DATE NOT NULL,
  OPTLOCK_VERSION INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_ITISEG_ITINERARY
        FOREIGN KEY (ITINERARY_ID)
        REFERENCES TEST_ITINERARY(ID)
);

CREATE TABLE TEST_TRAVELLER_ITINERARY
(
  TRAVELLER_ID NUMBER  NOT NULL,
  ITINERARY_ID NUMBER  NOT NULL
);

CREATE TABLE TEST_PAYMENT
(
  ID NUMBER NOT NULL,
  PAYMENT_TYPE VARCHAR(20) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(20),
  CARD_NUMBER VARCHAR(20),
  ITINERARY_ID INT,
  LAST_UPDATED_BY VARCHAR(30) NOT NULL,
  LAST_UPDATED DATE NOT NULL,
  OPTLOCK_VERSION INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_PAYMENT_ITINERARY
        FOREIGN KEY (ITINERARY_ID)
        REFERENCES TEST_ITINERARY(ID)
);

-- Create sequence
CREATE SEQUENCE TEST_BASE_DTO_SEQ
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
